apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: cornserve-system
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  type: NodePort
  ports:
  - port: 16686
    targetPort: 16686
    nodePort: 30686
    name: query
