apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: executiondescriptors.cornserve.ai
spec:
  group: cornserve.ai
  scope: Namespaced
  names:
    plural: executiondescriptors
    singular: executiondescriptor
    kind: ExecutionDescriptor
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                taskClassName:
                  type: string
                descriptorClassName:
                  type: string
                moduleName:
                  type: string
                sourceCode:
                  type: string
                isDefault:
                  type: boolean
                  default: true
              required: ["taskClassName", "descriptorClassName", "moduleName", "sourceCode"]
