apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-manager-binding
subjects:
- kind: ServiceAccount
  name: cornserve-sa
  namespace: cornserve
roleRef:
  kind: ClusterRole
  name: resource-manager-role
  apiGroup: rbac.authorization.k8s.io
