apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-dispatcher
  namespace: cornserve
  labels:
    app: task-dispatcher
spec:
  selector:
    matchLabels:
      app: task-dispatcher
  replicas: 3
  template:
    metadata:
      labels:
        app: task-dispatcher
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      containers:
      - name: task-dispatcher
        image: cornserve/task-dispatcher:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
          name: grpc
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: cornserve-config
