apiVersion: v1
kind: Service
metadata:
  name: task-dispatcher
  namespace: cornserve
spec:
  selector:
    app: task-dispatcher
  ports:
  - name: grpc
    port: 50051
    targetPort: grpc
  - name: http
    port: 8000
    targetPort: http
