apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: cornserve
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      containers:
      - name: gateway
        image: cornserve/gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: cornserve-config
        volumeMounts:
        - name: gateway-config-volume
          mountPath: /etc/cornserve
          readOnly: true
      volumes:
      - name: gateway-config-volume
        configMap:
          name: cornserve-gateway-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cornserve-gateway-config
  namespace: cornserve
data:
  gateway-routing.yaml: |
    eric-te-urls:
      - http://localhost:2379
    llm-te-urls:
      - http://localhost:2380
