apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: cornserve
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: cornserve/gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
