---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-cr-access
  namespace: cornserve
subjects:
- kind: ServiceAccount
  name: gateway-sa
  namespace: cornserve
roleRef:
  kind: Role
  name: gateway-cr-access-role
  apiGroup: rbac.authorization.k8s.io
