apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sidecar-binding
  namespace: cornserve
subjects:
- kind: ServiceAccount
  name: sidecar-sa
roleRef:
  kind: Role
  name: sidecar-role
  apiGroup: rbac.authorization.k8s.io

