# This file is not used by Kustomize; sidecars are deployed by the Resource Manager.
# We keep it here for reference. We might want to deploy only the sidecars, for instance.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sidecar
  namespace: cornserve
  labels:
    app: sidecar
spec:
  serviceName: sidecar
  selector:
    matchLabels:
      app: sidecar
  replicas: 4
  template:
    metadata:
      labels:
        app: sidecar
    spec:
      hostPID: true
      hostIPC: true
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: sidecar
      runtimeClassName: nvidia
      serviceAccountName: sidecar
      containers:
      - name: sidecar
        image: cornserve/sidecar:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
          - name: SIDECAR_WORLD_SIZE
            value: "4"
          - name: SIDECAR_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: cornserve-config
        volumeMounts:
          - name: shm-volume
            mountPath: /dev/shm
          - name: infiniband-class
            mountPath: /sys/class/infiniband
          - name: infiniband-dev
            mountPath: /dev/infiniband
      volumes:
      - name: shm-volume
        hostPath:
          path: /dev/shm
          type: Directory
      - name: infiniband-class
        hostPath:
          path: /sys/class/infiniband
          type: Directory
      - name: infiniband-dev
        hostPath:
          path: /dev/infiniband
          type: Directory
