apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gateway
- resource-manager
- sidecar
- task-dispatcher
- task-manager
- namespace.yaml
images:
- name: cornserve/gateway
  newName: cornserve/gateway
- name: cornserve/resource-manager
  newName: cornserve/resource-manager
- name: cornserve/sidecar
  newName: cornserve/sidecar
- name: cornserve/task-dispatcher
  newName: cornserve/task-dispatcher
- name: cornserve/task-manager
  newName: cornserve/task-manager
configMapGenerator:
- name: cornserve-config
  namespace: cornserve
  literals:
  - CORNSERVE_IMAGE_PREFIX=docker.io/cornserve
  - CORNSERVE_IMAGE_TAG=latest
  - CORNSERVE_IMAGE_PULL_POLICY=IfNotPresent
  - OTEL_SPAN_ATTRIBUTE_VALUE_LENGTH_LIMIT=2048
generatorOptions:
  disableNameSuffixHash: true
