apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-collector
  namespace: cornserve
  labels:
    app: jaeger-collector
spec:
  selector:
    matchLabels:
      app: jaeger-collector
  replicas: 1
  template:
    metadata:
      labels:
        app: jaeger-collector
    spec:
      containers:
      - name: jaeger-collector
        image: jaegertracing/jaeger-collector:latest
        imagePullPolicy: IfNotPresent
        args:
          - "--config-file=/config/config.yaml"
        volumeMounts:
          - name: config-volume
            mountPath: /config
        ports:
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        - containerPort: 14250
          name: jaeger-grpc
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 200Mi
      volumes:
        - name: config-volume
          configMap:
            name: jaeger-collector-config
