apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: cornserve
  labels:
    app: jaeger-collector
spec:
  selector:
    app: jaeger-collector
  ports:
  - port: 4317
    targetPort: 4317
    name: otlp-grpc
  - port: 4318
    targetPort: 4318
    name: otlp-http
  - port: 14250
    targetPort: 14250
    name: jaeger-grpc
