apiVersion: v1
kind: Service
metadata:
  name: gateway-node-port
  namespace: cornserve
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
  - name: gateway
    port: 8000
    targetPort: http
    nodePort: 30080
