apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: cornserve
  labels:
    app: otel-collector
spec:
  selector:
    matchLabels:
      app: otel-collector
  replicas: 1
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:latest
        imagePullPolicy: Always
        args:
        - --config=/conf/config.yaml
        ports:
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        - containerPort: 8888
          name: metrics
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /conf
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 200Mi
      volumes:
      - name: otel-collector-config-vol
        configMap:
          name: otel-collector-conf
