apiVersion: v1
kind: Service
metadata:
  name: registry-node-port
  namespace: cornserve-system
spec:
  type: NodePort
  selector:
    app: registry
  ports:
  - name: registry
    port: 5000
    targetPort: registry
    nodePort: 30070
