apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- gateway
patches:
- path: image-pull-policy.yaml
images:
- name: cornserve/gateway
  newName: localhost:5000/cornserve/gateway
  newTag: latest
- name: cornserve/resource-manager
  newName: localhost:5000/cornserve/resource-manager
  newTag: latest
- name: cornserve/sidecar
  newName: localhost:5000/cornserve/sidecar
  newTag: latest
- name: cornserve/task-dispatcher
  newName: localhost:5000/cornserve/task-dispatcher
  newTag: latest
- name: cornserve/task-manager
  newName: localhost:5000/cornserve/task-manager
  newTag: latest
configMapGenerator:
- name: cornserve-config
  namespace: cornserve
  behavior: merge
  literals:
  - CORNSERVE_IMAGE_PREFIX=localhost:5000/cornserve
  - CORNSERVE_IMAGE_PULL_POLICY=Always
  - CORNSERVE_IMAGE_TAG=latest
  # uncomment below to disable OTEL during benchmarking
  # - OTEL_SDK_DISABLED=true
