apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- gateway
patches:
- path: image-pull-policy.yaml
images:
- name: cornserve/gateway
  newName: 172.31.72.50:5000/cornserve/gateway
  newTag: latest
- name: cornserve/resource-manager
  newName: 172.31.72.50:5000/cornserve/resource-manager
  newTag: latest
- name: cornserve/sidecar
  newName: 172.31.72.50:5000/cornserve/sidecar
  newTag: latest
- name: cornserve/task-dispatcher
  newName: 172.31.72.50:5000/cornserve/task-dispatcher
  newTag: latest
- name: cornserve/task-manager
  newName: 172.31.72.50:5000/cornserve/task-manager
  newTag: latest
configMapGenerator:
- name: cornserve-config
  namespace: cornserve
  behavior: merge
  literals:
  - CORNSERVE_IMAGE_PREFIX=172.31.72.50:5000/cornserve
  - CORNSERVE_IMAGE_PULL_POLICY=Always
  - CORNSERVE_IMAGE_TAG=latest
  # uncomment below to disable OTEL during benchmarking
  - OTEL_SDK_DISABLED=true
  # - UCX_NET_DEVICES=rdmap16s27:1,rdmap32s27:1,rdmap144s27:1,rdmap160s27:1
  - UCX_MAX_EAGER_RAILS=4
  - UCX_MAX_RNDV_RAILS=4
  - UCX_RNDV_THRESH=8k
  - UCX_RNDV_FRAG_SIZE=host:1M
