apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- target:
    kind: Deployment
    labelSelector: app=jaeger
  patch: |-
    - op: remove
      path: /spec/template/spec/nodeSelector
components:
- jaeger
