apiVersion: v1
kind: Service
metadata:
  name: resource-manager-node-port
  namespace: cornserve
spec:
  type: NodePort
  selector:
    app: resource-manager
  ports:
  - name: resource-manager
    port: 50051
    targetPort: grpc
    nodePort: 30001
