apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: cornserve-system
  labels:
    app: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  replicas: 1
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      containers:
      - name: jaeger
        image: jaegertracing/jaeger:2.4.0
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        args:
          - "--config=/config/config.yaml"
        ports:
        - containerPort: 16686
          name: query
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        volumeMounts:
        - name: config-volume
          mountPath: /config
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 200Mi
      volumes:
      - name: config-volume
        configMap:
          name: jaeger-config
