apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: cornserve-system
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - port: 4317
    targetPort: 4317
    name: otlp-grpc
  - port: 4318
    targetPort: 4318
    name: otlp-http
