name: Test build vLLM

on:
  push:
    branches:
      - jm-reduce-eric-image
    tags:
      - v*
    paths:
      - '.github/workflows/test_build_vllm.yaml'
      - '.gitmodules'
      - 'docker/**'
      - 'python/**'
      - 'proto/**'
      - 'third_party/**'
      - 'scripts/generate_pb.sh'
      - '.dockerignore'
      - 'LICENSE'
      - 'setup.py'
      - 'pyproject.toml'

env:
  NAMESPACE: cornserve

jobs:
  build_and_push:
    if: github.repository_owner == 'cornserve-ai'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - vllm
        include:
          - component: vllm
            build_target: vllm

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 8

      - name: Check disk space and memory
        run: |
          df . -h
          free -h

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python for protobuf generation
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install protobuf dependencies
        run: pip install grpcio-tools==1.71.0

      - name: Generate protobuf files
        run: bash scripts/generate_pb.sh

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.NAMESPACE }}/${{ matrix.component }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=match,pattern=v.*

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/${{ matrix.component }}.Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          build-args: ${{ matrix.build_args }}
          target: ${{ matrix.build_target || '' }}
